import CustomersProvider from '@/Context/CustomersProvider/CustomersProvider';
import GlobalStateProvider from '@/Context/GlobalStateProvider/GlobalStateProvider';
import ProductInfoProvider from '@/Context/ProductInfoProvider/ProductInfoProvider';
import NavigationBar from '@/layouts/NavigationBar/NavigationBar';
import '@/styles/global.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { CssBaseline } from '@mui/material';
import Head from 'next/head';
import 'toastify-js/src/toastify.css';

export default function App({ Component, pageProps }) {
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <CssBaseline />
         <GlobalStateProvider>
            <CustomersProvider>
               <ProductInfoProvider>
                  <NavigationBar />
                  <Component {...pageProps} />
               </ProductInfoProvider>
            </CustomersProvider>
         </GlobalStateProvider>
      </>
   );
}
